#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/sikyozo
#    username: root
#    password: Yeji@@98216!!
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update  # DB 스키마 자동 업데이트
#    show-sql: true  # SQL 쿼리 로그를 출력
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true  # SQL 쿼리를 포맷하여 보기 쉽게 출력
#        use_sql_comments: true
#
#jwt:
#  secret: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
#  token:
#    access-expiration-time: 43200000    # 12시간
#    refresh-expiration-time: 604800000  # 7일